linters:
  enable-all: true
  disable:
    - exportloopref # deprecated
    - copyloopvar # too modern
    - intrange    # too modern
    - depguard    # too smart
    - godox       # has to be enabled

linters-settings:
#  gci:
#    sections:
#      - standard
#      - default
#      - prefix(github.com/michurin/ngramindex)
  lll: {line-length: 200}
#  funlen: {statements: 150, lines: 150} # parsers are long
#  cyclop: {max-complexity: 50}          # and "complex"
