version: "2"
linters:
  default: all
  disable:
    - copyloopvar # too modern
    - godox       # has to be enabled
    - intrange    # too modern
  settings:
    lll:
      line-length: 200
    depguard:
      rules:
        test:
          files:
            - "*_test.go"
          allow:
            - github.com/michurin/ngramindex
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
