version: "2"
linters:
  default: all
  disable:
    - copyloopvar # too modern
    - godox       # has to be enabled
    - intrange    # too modern
    - revive      # nice to be enabled
    - wsl         # deprecated due to wsl_v5
  settings:
    lll:
      line-length: 200
    depguard:
      rules:
        test:
          files:
            - "$test"
          allow:
            - "$gostd"
            - github.com/michurin/ngramindex
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
