---
name: codecov # this string appears on badge
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Upload coverage reports to Codecov"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - run: "go test -coverprofile=coverage.txt -covermode=atomic ."
      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage.txt
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }} # required
